name: Publish to npm and GitHub Release

on:
  push:
    branches:
      - main

permissions:
  contents: write # Grants permission to push code, commits, and tags
  issues: write

jobs:
  macos-build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build macOS binary
        run: npm run build:macos

      - name: Package binary using node-pre-gyp
        run: npm run package:binary

      - name: Publish binary to GitHub Releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.NODE_PRE_GYP_GITHUB_TOKEN }}
        run: npm run publish:binary
      # Publish to npm (after binaries are built and uploaded)
      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public

      # Bump version automatically
      - name: Bump version
        run: npm version patch

      # Get the latest tag
      - name: Get latest tag
        id: get_tag
        run: echo "::set-output name=tag::$(git describe --tags --abbrev=0)"

      # Create a new release on GitHub using the pushed tag
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2.0.8
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }} # Dynamically use the latest tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
