name: Publish to npm and GitHub Release

on:
  push:
    branches:
      - master

permissions:
  contents: write
  issues: write

jobs:
  publish:
    runs-on: macos-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensure all history and tags are fetched

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Install node-pre-gyp-github globally
      - name: Install node-pre-gyp-github
        run: npm install -g node-pre-gyp-github

      # Build macOS binary
      - name: Build macOS binary
        run: npm run build:macos

      # Package binary using node-pre-gyp
      - name: Package binary
        run: npm run package:binary

      # Publish binary to GitHub Releases
      - name: Publish binary to GitHub Releases
        env:
          NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.NODE_PRE_GYP_GITHUB_TOKEN }}
        run: node-pre-gyp-github publish --release

      # Set Git user identity (for version bump commit)
      - name: Set Git user identity
        run: |
          git config --global user.name "Timeo Williams"
          git config --global user.email "timwillie73@gmail.com"

      # Commit any changes
      - name: Commit changes
        run: |
          git add .
          git commit -m "Committing changes from build" || echo "No changes to commit"

      # Bump the package version
      - name: Bump version
        run: npm version patch

      # Push version commit and tag to GitHub
      - name: Push version commit and tag
        run: |
          git push origin ${{ github.ref_name }} --tags

      # Publish to npm
      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
