name: Publish to npm and GitHub Release

on:
  push:
    branches:
      - main

permissions:
  contents: write # Grants permission to push code, commits, and tags
  issues: write

jobs:
  publish:
    runs-on: macos-latest # Ensure macOS for macOS builds

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Install node-pre-gyp-github globally
      - name: Install node-pre-gyp-github
        run: npm install -g node-pre-gyp-github

      # Build the macOS binary
      - name: Build macOS binary
        run: npm run build:macos

      # Package binary using node-pre-gyp
      - name: Package binary
        run: npm run package:binary

      # Publish binary to GitHub Releases
      - name: Publish binary to GitHub Releases
        env:
          NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.NODE_PRE_GYP_GITHUB_TOKEN }}
        run:
          node-pre-gyp-github publish

          # Set Git user identity (for version bump commit)
      - name: Set Git user identity
        run: |
          git config --global user.name "Timeo Williams"
          git config --global user.email "timwillie73@gmail.com"
        # Bump the package version
      - name: Bump version
        run: npm version patch

        # Push version commit and tag to GitHub
      - name: Push version commit and tag
        run: |
          git push origin main --tags

        # Fetch all tags to make sure the latest tag is available
      - name: Fetch all tags
        run: git fetch --tags

        # Publish to npm
      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
